### 全局变量
@baseUrl = http://localhost:8080/api
@contentType = application/json


### 0.1 注册新用户 (如果还没有账号)
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "username": "Haoyi Zhou",
  "email": "23@buaaa.edu.cn",
  "password": "123456"
}

### 0.2 登录获取 Token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "account": "Haoyi Zhou",
  "password": "123456"
}

### 变量赋值：自动从登录响应中提取 Token
# 假设 LoginResponse 结构包含 token 字段
@token = {{login.response.body.data.token}}



###
POST {{baseUrl}}/rankingjobs/generate-rankings
Authorization: Bearer {{token}}